#!/bin/bash

SERVERS="
10.2.2.12
"
CLIENTS="
10.2.2.18
"
ROUTER="10.2.2.3"
USER="ubuntu"
HOME_DIR="/home/${USER}"
CCNX_DIR="${HOME_DIR}/ccnx-0.7.1"
NAMELIST_DIR="${HOME_DIR}/onl_ccnx_utils"
NAMELIST="namelist"
NAMELIST_PREFIX="ccnx:/gen"
UNIQUE=1
CCNDC_PROTO="tcp"
CCNDC_FLAG=""
CCNDC_PORT="" #default port: 9695
CCND_OUTPUT="result.out"

source $1

