#!/bin/bash

# Need: SERVERS, CLIENTS, ROUTER, USER, CCNX_DIR,
#       NAMELIST_DIR, NAMELIST, NAMELIST_PREFIX
#       UNIQUE, CCNDC_PROTO, CCNDC_FLAG, CCNDC_PORT
#       CCND_OUTPUT

# Note: redirecting stdout and stderr to /dev/null
#       is necessary esp. on clients/servers to avoid
#       sending unnecessary information through ssh
#       to local terminal, which degrades performance
#       severely

source stopall
#source initall

echo "Run ccndstart on router(local).."
cd ${CCNX_DIR}/bin
./ccndstart &> /dev/null

echo "Setting up all servers.."
COUNT=0
for ip in $SERVERS
do
	echo "  working on: ${ip}"
	(( COUNT+=1 ))

	# find prefix. typically:
	#     ccnx:/gen if UNIQUE is 0
	#     ccnx:/gen/${COUNT} otherwise
	PREFIX=${NAMELIST_PREFIX}
	if [[ $UNIQUE -ne 0 ]]
	then
		PREFIX="${NAMELIST_PREFIX}/${COUNT}"
	fi

	# for each server..
	#   start ccnd service
	ssh ${USER}@${ip} -f "
		cd ${CCNX_DIR}/bin
		./ccndstart &> /dev/null
		./ccndelphi ${PREFIX} &> /dev/null
	"

	# ccndc from router to servers
	sleep 2
	cd ${CCNX_DIR}/bin
	./ccndc ${CCNDC_FLAG} add ${PREFIX} ${CCNDC_PROTO} ${ip} ${CCNDC_PORT}
	
done 

echo "Setting up all clients.."
COUNT=0
for ip in $CLIENTS
do
	echo "  working on: ${ip}"
	(( COUNT+=1 ))

	# find prefix. typically:
	#     ccnx:/gen if UNIQUE is 0
	#     ccnx:/gen/${COUNT} otherwise
	PREFIX=${NAMELIST_PREFIX}
	if [[ $UNIQUE -ne 0 ]]
	then
		PREFIX="${NAMELIST_PREFIX}/${COUNT}"
	fi

	# for each client..
	#   create namelists
	#   start ccnd service
	#   ccndc to router
	ssh ${USER}@${ip} -f "
		cd ${NAMELIST_DIR}
		./create_namelist.sh ${NAMELIST} ${PREFIX} ${NAMELIST_NUM}
		cd ${CCNX_DIR}/bin
		./ccndstart &> /dev/null
		./ccndc ${CCNDC_FLAG} add ${PREFIX} ${CCNDC_PROTO} ${ROUTER} ${CCNDC_PORT}
		./ccntraffic -f ${NAMELIST_DIR}/${NAMELIST} -n ${NAMELIST_NUM} &> /dev/null

	"

done


